name: Build and deploy storybook
on:
  push:
    branches:
      - main

jobs:
  storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install package dependencies
        run: bun install

      - name: Build package and storybook
        run: bun build-storybook && touch storybook-static/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: storybook-static
          branch: gh-pages
          clean-exclude: pr-preview
          force: false
