name: Build and deploy storybook
on:
  push:
    branches:
      - main
    paths:
      - "packages/too-many-hooks/**"
      - "packages/storybook/**"

jobs:
  storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install package dependencies
        run: bun install

      - name: Build package
        run: bun run build
        working-directory: packages/too-many-hooks

      - name: Build storybook
        run: bun build-storybook && touch storybook-static/.nojekyll
        working-directory: packages/storybook

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: packages/storybook/storybook-static
          branch: gh-pages
          clean-exclude: pr-preview
          force: false
