name: Build and deploy storybook
on:
  push:
    branches:
      - main
    paths:
      - "packages/too-many-hooks/**"
      - "packages/storybook/**"

jobs:
  storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Restore yarn cache
        uses: c-hive/gha-yarn-cache@v2

      - name: Install package dependencies
        run: yarn install

      - name: Build package
        run: yarn build
        working-directory: packages/too-many-hooks

      - name: Build storybook
        run: yarn build-storybook && touch storybook-static/.nojekyll
        working-directory: packages/storybook

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: packages/storybook/storybook-static
          branch: gh-pages
          clean-exclude: pr-preview
          force: false
