name: Lint and build storybook
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - "packages/storybook/**"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Restore package lint cache
        id: package-lint
        uses: actions/cache@v3
        with:
          path: packages/too-many-hooks/lint-cache
          key: ${{ runner.os }}-package-lint

      - name: Install package dependencies
        run: bun install

      - name: Build package
        run: bun run build
        working-directory: packages/too-many-hooks

      - name: Restore storybook lint cache
        id: storybook-lint
        uses: actions/cache@v3
        with:
          path: packages/storybook/lint-cache
          key: ${{ runner.os }}-storybook-lint

      - name: Lint
        run: bun lint
        working-directory: packages/storybook

      - name: Build
        run: bun build-storybook
        working-directory: packages/storybook
