name: Lint and build package
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - "packages/too-many-hooks/**"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Restore lint cache
        id: package-lint
        uses: actions/cache@v3
        with:
          path: packages/too-many-hooks/lint-cache
          key: ${{ runner.os }}-package-lint

      - name: Install dependencies
        run: bun install
        working-directory: packages/too-many-hooks

      - name: Lint
        run: bun lint
        working-directory: packages/too-many-hooks

      - name: Build
        run: bun run build
        working-directory: packages/too-many-hooks
