name: Preview storybook in PR
concurrency: preview-${{ github.ref }}
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - closed
    paths:
      - "packages/too-many-hooks/**"
      - "packages/storybook/**"

jobs:
  storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install package dependencies
        run: bun install

      - name: Build package
        run: bun run build
        working-directory: packages/too-many-hooks

      - name: Build storybook
        run: bun build-storybook
        working-directory: packages/storybook

      - name: Deploy to PR Preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: packages/storybook/storybook-static
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto
