name: Preview storybook in PR
concurrency: preview-${{ github.ref }}
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - closed
    paths:
      - "packages/too-many-hooks/**"
      - "packages/storybook/**"

jobs:
  storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Restore yarn cache
        uses: c-hive/gha-yarn-cache@v2

      - name: Install package dependencies
        run: yarn install

      - name: Build package
        run: yarn build
        working-directory: packages/too-many-hooks

      - name: Build storybook
        run: yarn build-storybook
        working-directory: packages/storybook

      - name: Deploy to PR Preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: packages/storybook/storybook-static
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto
