name: Preview storybook in PR
concurrency: preview-${{ github.ref }}
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - closed

jobs:
  storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install package dependencies
        run: bun install

      - name: Build package and storybook
        run: bun build-storybook

      - name: Deploy to PR Preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: storybook-static
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto
